language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
before_install:
  - git clone -b iterative_uniquify https://github.com/clemux/firewoes.git
  - pip install -e firewoes
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
