language: python
python:
  - "2.7"
#  - "3.3"
# command to install dependencies
before_install:
  - git clone -b iterative_uniquify https://github.com/clemux/firewoes.git ../firewoes
  - pip install -e ../firewoes
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8
env:
  - DATABASE_URI='postgres://postgres:@localhost:5432/debile_tests'
before_script:
  - flake8 --version
  - cat ~/.config/flake8
  - psql -c 'create database debile_tests;' -U postgres

# command to run tests
script:
 - coverage run --source=. $(which nosetests)

# flake8
# warnings ignored:
# * E241 (multiple spaces after ':', ',') -> we want to align stuff
 - flake8 debile/ --ignore E711,E241 --max-line-length=200
after_success:
 - coveralls
